install: all
	cp -f auto-rotate_screen.sh /usr/local/bin/
	cp -f getBrightness.sh /usr/local/bin/
	cp -f tizonia-ctl.sh /usr/local/bin/
	cp -f dmenu_pass /usr/local/bin/

uninstall:
	rm -f /usr/local/bin/auto-rotate_screen.sh
	rm -f /usr/local/bin/getBrightness.sh
	rm -f /usr/local/bin/tizonia-ctl.sh

.PHONY: all install uninstall
